repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0  # Use the latest stable version
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0  # Use the latest stable version
    hooks:
      - id: flake8
        args: [--max-line-length=88]  # Match Black's formatting

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest stable version
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
      - id: pylint
